-- Run in Supabase SQL Editor (or via migrations) before using the app.
-- Enables per-user tasks with RLS.

create table tasks
(
    created_at   timestamp with time zone default now() not null,
    updated_at   timestamp,
    title        text                                   not null,
    body         text,
    user_id      uuid                                   not null
        constraint todos_user_id_fkey
            references auth.users
            on update cascade on delete cascade,
    id           bigint generated by default as identity
        constraint todos_pkey
            primary key
        constraint todos_new_id_key
            unique,
    completed_at timestamp
);

alter table tasks
    owner to postgres;

create policy "Enable users to view their own data only" on tasks
    as permissive
    for select
    to authenticated
    using ((SELECT auth.uid() AS uid) = user_id);

create policy "Enable insert for users based on user_id" on tasks
    as permissive
    for insert
    with check ((SELECT auth.uid() AS uid) = user_id);

create policy "Enable users to update their own data only" on tasks
    as permissive
    for update
    to authenticated
    using ((SELECT auth.uid() AS uid) = user_id);

create policy "Enable delete for users based on user_id" on tasks
    as permissive
    for delete
    using ((SELECT auth.uid() AS uid) = user_id);

alter table tasks enable row level security;
